# Generated by Django 2.2.20 on 2021-04-28 15:44

from django.db import migrations, models
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_serve_uploads_by_django_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimagemodel',
            name='name',
            field=models.CharField(blank=True, help_text='BaseItemAttachmentModel.name.help_text', max_length=255, null=True, verbose_name='BaseItemAttachmentModel.name.verbose_name'),
        ),
        migrations.CreateModel(
            name='Tagulous_BaseItemAttachmentModel_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
    ]
