# Generated by Django 3.1.13 on 2021-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlinkmodel',
            name='last_check',
            field=models.DateTimeField(blank=True, editable=False, help_text='Link.url.help_text', null=True, verbose_name='Link.url.verbose_name'),
        ),
    ]
