# Generated by Django 3.1.13 on 2021-11-22 17:47

from django.db import migrations
import django_tools.model_version_protect.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='version',
            field=django_tools.model_version_protect.models.VersionModelField(default=0, help_text='Internal version number of this entry. Used to protect the overwriting of an older entry.'),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='version',
            field=django_tools.model_version_protect.models.VersionModelField(default=0, help_text='Internal version number of this entry. Used to protect the overwriting of an older entry.'),
        ),
        migrations.AddField(
            model_name='memomodel',
            name='version',
            field=django_tools.model_version_protect.models.VersionModelField(default=0, help_text='Internal version number of this entry. Used to protect the overwriting of an older entry.'),
        ),
    ]
