version: "3.7"

services:
    caddy: # https://hub.docker.com/_/caddy
        environment:
            - HOSTNAME=localhost
            - LETSENCRYPT_EMAIL=internal

    django:
        environment:
            - DJANGO_SETTINGS_MODULE=docker_settings
            - HOSTNAME=localhost
        volumes:
            - ./dist/:/dist/
