version: "3.7"

services:
    caddy: # https://hub.docker.com/_/caddy
        environment:
            - HOSTNAME=localhost
            - LETSENCRYPT_EMAIL=internal

    inventory:
        environment:
            - DJANGO_SETTINGS_MODULE=docker_settings
            - HOSTNAME=localhost
        links:
            - postgres:postgres
        depends_on:
            - postgres
            - caddy
        volumes:
            - ./dist/:/dist/
