# Generated by Django 2.2.16 on 2020-10-17 20:11

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlinkmodel',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, case_sensitive=False, force_lowercase=False, help_text='BaseModel.tags.help_text', max_count=10, space_delimiter=False, to='inventory.Tagulous_ItemLinkModel_tags', verbose_name='BaseModel.tags.verbose_name'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='kind',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, force_lowercase=False, help_text='ItemModel.kind.help_text', max_count=3, space_delimiter=False, to='inventory.Tagulous_ItemModel_kind', verbose_name='ItemModel.kind.verbose_name'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='producer',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, case_sensitive=False, force_lowercase=False, help_text='ItemModel.producer.help_text', max_count=1, space_delimiter=False, to='inventory.Tagulous_ItemModel_producer', verbose_name='ItemModel.producer.verbose_name'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, case_sensitive=False, force_lowercase=False, help_text='BaseModel.tags.help_text', max_count=10, space_delimiter=False, to='inventory.Tagulous_ItemModel_tags', verbose_name='BaseModel.tags.verbose_name'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, case_sensitive=False, force_lowercase=False, help_text='BaseModel.tags.help_text', max_count=10, space_delimiter=False, to='inventory.Tagulous_LocationModel_tags', verbose_name='BaseModel.tags.verbose_name'),
        ),
    ]
