# Generated by Django 2.2.16 on 2020-10-24 16:30


from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0002_auto_20201017_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='description',
            field=TextField(
                blank=True,
                help_text='LocationModel.description.help_text',
                null=True,
                verbose_name='LocationModel.description.verbose_name',
            ),
        ),
    ]
