# Generated by Django 3.2.14 on 2022-07-21 18:36
from django.core import management
from django.db import migrations

from inventory.management.commands import tree


def forward_code(apps, schema_editor):
    management.call_command(tree.Command(), model_name='itemmodel')
    management.call_command(tree.Command(), model_name='locationmodel')


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0011_parent_tree1'),
    ]

    operations = [
        migrations.RunPython(forward_code, reverse_code=migrations.RunPython.noop),
    ]
