# Generated by Django 3.2.15 on 2022-09-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0012_parent_tree2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='location',
            field=models.ForeignKey(
                blank=True,
                help_text='ItemModel.location.help_text',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='items',
                to='inventory.locationmodel',
                verbose_name='ItemModel.location.verbose_name',
            ),
        ),
    ]
