# Generated by Django 5.1.1 on 2024-09-05 17:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_itemmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='description',
            field=tinymce.models.HTMLField(
                blank=True,
                help_text='ItemModel.description.help_text',
                null=True,
                verbose_name='ItemModel.description.verbose_name',
            ),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='description',
            field=tinymce.models.HTMLField(
                blank=True,
                help_text='LocationModel.description.help_text',
                null=True,
                verbose_name='LocationModel.description.verbose_name',
            ),
        ),
        migrations.AlterField(
            model_name='memomodel',
            name='memo',
            field=tinymce.models.HTMLField(
                blank=True,
                help_text='MemoModel.description.help_text',
                null=True,
                verbose_name='MemoModel.description.verbose_name',
            ),
        ),
    ]
