# Generated by Django 5.1.12 on 2025-10-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_itemmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMainCategory',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ItemMainCategory.name.help_text', max_length=32, unique=True, verbose_name='ItemMainCategory.name.verbose_name')),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ItemMainCategory.verbose_name',
                'verbose_name_plural': 'ItemMainCategory.verbose_name_plural',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='ItemModel.category.help_text', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemmaincategory', verbose_name='ItemModel.category.verbose_name'),
        ),
    ]
